import Head from 'next/head'
import styles from '@/styles/Home.module.css';
import { GraphQLClient, gql } from 'graphql-request';
import BlogCard from './components/BlogCard';

const graphcms = new GraphQLClient("https://api-us-west-2.hygraph.com/v2/clfsoo4kq26ga01t714pq4g9a/master");

const QUERY = gql`
  {
    posts {
      id
      title
      datePublish
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        createdBy {
          id
        }
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 30,
  };
};

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Sara's Art Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard 
          title={post.title}
          author={post.author}
          coverPhoto={post.coverPhoto}
          key={post.id}
          datePublish={post.datePublish}
          slug={post.slug}
          />
        ))}
      </main>
    </>
  );
};
